# Generated by Django 2.1.7 on 2019-05-05 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20190504_2318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventcard',
            old_name='description',
            new_name='big_description',
        ),
        migrations.AddField(
            model_name='eventcard',
            name='small_description',
            field=models.CharField(default='String', max_length=500),
        ),
    ]
