# Generated by Django 2.2.1 on 2019-05-14 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_auto_20190514_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to='attachment_files'),
        ),
        migrations.AlterField(
            model_name='board',
            name='image',
            field=models.ImageField(default='default-board.jpg', upload_to='board-imgs'),
        ),
    ]
