# Generated by Django 2.2.1 on 2019-05-15 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_auto_20190514_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(blank=True, upload_to='attachment_files'),
        ),
        migrations.AlterField(
            model_name='eventcard',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
